knp_paginator:
  page_range: 5                       # Nombre de pages affichées dans la barre de pagination
  default_options:
    page_name: page                 # Nom du paramètre de requête pour la page
    sort_field_name: sort           # Nom du paramètre de requête pour le tri
    sort_direction_name: direction  # Nom du paramètre de requête pour la direction de tri
    distinct: true                  # Définir à true pour éviter de compter les doublons
  template:
    pagination: '@KnpPaginator/Pagination/sliding.html.twig'   # Modèle de pagination à utiliser
